spring.application.name=product-service
server.port=7778

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

spring.datasource.url=jdbc:postgresql://localhost:5432/Assessment
spring.datasource.username=postgres
spring.datasource.password=rrj

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=*