spring.application.name=SprintAssisment3_28March

spring.datasource.url=jdbc:postgresql://localhost:5432/MappingDB
spring.datasource.username=sharthaksharma
spring.datasource.password=Sarthak@52

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

server.port=8080