spring.application.name=user-service

server.port=7774

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/Assessment
spring.datasource.username=postgres
spring.datasource.password=rrj

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=*